# Generated by Django 5.2.11 on 2026-03-01 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CellReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cell_id", models.CharField(max_length=64)),
                (
                    "grid_type",
                    models.CharField(
                        choices=[
                            ("stat_250m", "Statistical 250m"),
                            ("stat_1km", "Statistical 1km"),
                            ("stat_5km", "Statistical 5km"),
                            ("h3_res10", "H3 ~44m"),
                            ("h3_res9", "H3 ~175m"),
                            ("h3_res8", "H3 ~460m"),
                            ("h3_res7", "H3 ~1.2km"),
                            ("h3_res6", "H3 ~3.2km"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("dangerous", "Dangerous"),
                            ("no_ground_access", "No ground access"),
                            ("closed", "Closed"),
                            ("restricted", "Restricted"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("player_token", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cell_id", "grid_type", "player_token"),
                        name="unique_report_per_player",
                    )
                ],
            },
        ),
    ]
