# Generated by Django 5.2.11 on 2026-02-24 13:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_rename_grid_size_to_grid_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="player_token",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
