# Generated by Django 5.2.11 on 2026-02-27 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_area_game_play_area_alter_game_center_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="snapshot_cell_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="board",
            name="grid_type",
            field=models.CharField(
                choices=[
                    ("stat_250m", "Statistical 250m"),
                    ("stat_1km", "Statistical 1km"),
                    ("stat_5km", "Statistical 5km"),
                    ("h3_res10", "H3 ~44m"),
                    ("h3_res9", "H3 ~175m"),
                    ("h3_res8", "H3 ~460m"),
                    ("h3_res7", "H3 ~1.2km"),
                    ("h3_res6", "H3 ~3.2km"),
                ],
                default="h3_res9",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="grid_type",
            field=models.CharField(
                choices=[
                    ("stat_250m", "Statistical 250m"),
                    ("stat_1km", "Statistical 1km"),
                    ("stat_5km", "Statistical 5km"),
                    ("h3_res10", "H3 ~44m"),
                    ("h3_res9", "H3 ~175m"),
                    ("h3_res8", "H3 ~460m"),
                    ("h3_res7", "H3 ~1.2km"),
                    ("h3_res6", "H3 ~3.2km"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="BoardCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cell_id", models.CharField(max_length=64)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="game.board",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["board", "is_enabled"],
                        name="game_boardc_board_i_bf8933_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("board", "cell_id"), name="unique_board_cell"
                    )
                ],
            },
        ),
    ]
